spring.application.name=SkillExam
spring.datasource.url=jdbc:mysql://localhost:3306/fsadexam
spring.datasource.username=root
spring.datasource.password=Sistla@1974

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=2026